basic:
    name: 'Teste JS'
    environments:
        production: 'https://aletria.pt/'
        staging: 'https://aletria.dev11.javali.pt/'
        development: ''
    breakpoints:
        - 1366
    pages:
        - /
        - '#menu'
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: '.banner-container .slick-slide'
    isolate: .cookiesjsr-banner
    delay: 20
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: "setTimeout(function () {\n  if (window.location.hash === '#menu') {\n    const btn = document.querySelector('#nav-icon2');\n    if (btn) {\n      // Simula evento real de clique mais completo\n      btn.dispatchEvent(new MouseEvent('mouseover', { bubbles: true }));\n      btn.dispatchEvent(new MouseEvent('mousedown', { bubbles: true }));\n      btn.dispatchEvent(new MouseEvent('mouseup', { bubbles: true }));\n      btn.dispatchEvent(new MouseEvent('click', { bubbles: true }));\n    }\n    \n    const menu = document.querySelector('.region.region-header');\n    if (menu) {\n      menu.classList.add('active');\n      menu.style.display = 'block';\n      menu.style.opacity = '1';\n      menu.style.visibility = 'visible';\n      menu.style.height = 'auto';\n      menu.style.overflow = 'visible';\n    }\n  }\n}, 2000);\n"
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
