basic:
    name: 'Teste JS'
    environments:
        production: 'https://aletria.pt/'
        staging: 'https://aletria.dev11.javali.pt/'
        development: ''
    breakpoints:
        - 1366
    pages:
        - /
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: .cookiesjsr-banner
    delay: 20
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: "setTimeout(function () {\n  const btn = document.querySelector('#nav-icon2');\n  const container = document.querySelector('.container-menu');\n  if (btn) {\n    // Tenta simular clique com eventos mouse para forçar abrir\n    btn.dispatchEvent(new MouseEvent('mouseover', { bubbles: true }));\n    btn.dispatchEvent(new MouseEvent('mousedown', { bubbles: true }));\n    btn.dispatchEvent(new MouseEvent('mouseup', { bubbles: true }));\n    btn.dispatchEvent(new MouseEvent('click', { bubbles: true }));\n    btn.classList.add('open');\n  }\n  if (container) {\n    container.classList.add('open');\n    container.style.display = 'block';\n    container.style.opacity = '1';\n    container.style.visibility = 'visible';\n    container.style.height = 'auto';\n    container.style.overflow = 'visible';\n  }\n}, 3000);\n"
    custom_css: "/*if (window.location.hash === '#menu') {\n  setTimeout(function () {\n    const btn = document.querySelector('#nav-icon2');\n    if (btn) {\n      btn.click();\n    }\n  }, 1000); \n}\n*/"
    mock_content:
        - { selector: '', type: title }
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
